spring:
    application:
        name: MICROSERVICE2
        
server:
    port: 8086
    
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://65.1.113.48:8761/eureka
